### ISSUE TITLE
Import failure

### ISSUE THREAD

**Issue by CEllis40** [rsheftel/pandas_market_calendars#149]
I have Python 3.7.11 and numpy 1.20.3. When importing this package, I get the following error:

>>> import pandas_market_calendars as mcal
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas_market_calendars\__init__.py", line 19, in <module>
    from .calendar_registry import get_calendar, get_calendar_names
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas_market_calendars\calendar_registry.py", line 21, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas_market_calendars\trading_calendars_mirror.py", line 11, in <module>
    import trading_calendars
  File "C:\ProgramData\Anaconda3\lib\site-packages\trading_calendars\__init__.py", line 16, in <module>
    from .trading_calendar import TradingCalendar
  File "C:\ProgramData\Anaconda3\lib\site-packages\trading_calendars\trading_calendar.py", line 33, in <module>
    from .calendar_helpers import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\trading_calendars\calendar_helpers.py", line 6, in <module>
    NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'

Any ideas for a fix?

**Comment by rsheftel** [comment]
#143 explains the issue and solution
