### ISSUE TITLE
Good Friday is always a holiday for CBOE/CFE even when Christmas and NYE fall on a Friday

### ISSUE THREAD

**Issue by ypsah** [rsheftel/pandas_market_calendars#312]
Good Friday is always a holiday, and #116 misinterpreted the spec.

Holiday reminders from CBOE for good fridays in 2020 and 2021:
- https://cdn.cboe.com/resources/schedule_update/2020/Cboe-Holiday-Reminder-Closed-on-Friday-April-10-2020.pdf
- https://cdn.cboe.com/resources/schedule_update/2021/Reminder-CFE-Modified-Trading-Hours-for-Good-Friday-2021-Notice.pdf

These two holidays are not reported as such in the latest version (`4.3.2`):

```python-console
>>> import pandas_market_calendars as mcal
>>> no_valid_days = mcal.get_calendar("CBOE_Index_Options").valid_days("2020-04-10", "2020-04-10")
>>> assert no_valid_days.empty, f"{no_valid_days} should not be a valid day"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: DatetimeIndex(['2020-04-10 00:00:00+00:00'], dtype='datetime64[ns, UTC]', freq='C') should not be a valid day
```

```python-console
>>> import pandas_market_calendars as mcal
>>> no_valid_days = mcal.get_calendar("CBOE_Index_Options").valid_days("2021-04-02", "2021-04-02")
>>> assert no_valid_days.empty, f"{no_valid_days} should not be a valid day"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: DatetimeIndex(['2021-04-02 00:00:00+00:00'], dtype='datetime64[ns, UTC]', freq='C') should not be a valid day
```

To further back this up: `exchange-calendars` reverted the change introduced for #116 in https://github.com/gerrymanoim/exchange_calendars/pull/121.

-----

Thank you for making `pandas-market-calendars`.

**Comment by ShiyuanZh** [comment]
Hi @rsheftel, what @ypsah said should be correct. Is there any plan for fixing this issue? Thank you for making this package.
