### ISSUE TITLE
ValueError getting schedule

### ISSUE THREAD

**Issue by llevar** [rsheftel/pandas_market_calendars#38]
On master

```
>>> cal = nyse.schedule(start_date='1950-01-03', end_date='2018-05-18')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas_market_calendars/market_calendar.py", line 213, in schedule
    _overwrite_special_dates(_all_days, closes, _special_closes)
  File "pandas_market_calendars/market_calendar.py", line 363, in _overwrite_special_dates
    raise ValueError("Special dates %s are not trading days." % bad_dates)
ValueError: Special dates [Timestamp('1956-12-24 19:00:00+0000', tz='UTC')] are not trading days.
```

I was expecting a valid schedule returned.

**Comment by rsheftel** [comment]
Thanks for reporting this error. It is fixed in the latest release (a1c6d21151997b6ebd24b4be5c472c6186d2c434) and uploaded to PyPi
