### ISSUE TITLE
RuntimeError: Class NYSE is not one of the registered classes: dict_keys(['MarketCalendar'])

### ISSUE THREAD

**Issue by haroldfox** [rsheftel/pandas_market_calendars#90]
Here is something that worked prior to v1.3 on python 3.6:

>>> import pandas_market_calendars as mcal
>>> nyse = mcal.get_calendar('NYSE')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.6/site-packages/pandas_market_calendars/calendar_registry.py", line 13, in get_calendar
    return MarketCalendar.factory(name, open_time=open_time, close_time=close_time)
  File "/lib/python3.6/site-packages/pandas_market_calendars/market_calendar.py", line 55, in factory
    return cls._regmeta_instance_factory(name, open_time=open_time, close_time=close_time)
  File "/lib/python3.6/site-packages/pandas_market_calendars/class_registry.py", line 22, in _regmeta_instance_factory
    return cls._regmeta_class_factory(name)(*args, **kwargs)
  File "/lib/python3.6/site-packages/pandas_market_calendars/class_registry.py", line 11, in _regmeta_class_factory
    'Class {} is not one of the registered classes: {}'.format(name, cls._regmeta_class_registry.keys()))
RuntimeError: Class NYSE is not one of the registered classes: dict_keys(['MarketCalendar'])

**Comment by michaeljsong99** [comment]
I have the same issue. Was also working for me yesterday, but not today.

**Comment by rsheftel** [comment]
This is fixed in c033ab8f85d262bcdcb383e0c214dc80ff3ba6c1 and pushed to PyPi as v1.3.1
